import {
  AlertCircleIcon,
  BoxIcon,
  LayersIcon,
  PaletteIcon,
  ToggleLeftIcon,
  TypeIcon,
} from "lucide-react";

export const VARIANTS = ["solid", "outline", "soft", "ghost", "link"] as const;
export const COLORS = [
  "primary",
  "secondary",
  "destructive",
  "warning",
  "success",
  "info",
  "tertiary",
] as const;
export const SIZES = ["sm", "md", "lg"] as const;

export const NAV = [
  { id: "overview", label: "Tổng quan", icon: LayersIcon },
  { id: "buttons", label: "Nút bấm", icon: BoxIcon },
  { id: "forms", label: "Biểu mẫu", icon: TypeIcon },
  { id: "feedback", label: "Phản hồi", icon: AlertCircleIcon },
  { id: "display", label: "Hiển thị", icon: PaletteIcon },
  { id: "interactive", label: "Tương tác", icon: ToggleLeftIcon },
];

export const STATS = [
  { label: "Components", value: "55" },
  { label: "Tokens", value: "40+" },
  { label: "Variants", value: "5×7" },
  { label: "Dark Mode", value: "✓" },
];

export const COLOR_INFO = {
  primary: { label: "Primary", description: "Hành động chính" },
  secondary: { label: "Secondary", description: "Thay thế / Phụ" },
  destructive: { label: "Destructive", description: "Nguy hiểm / Xóa" },
  warning: { label: "Warning", description: "Cảnh báo" },
  success: { label: "Success", description: "Thành công / Hoàn tất" },
  info: { label: "Info", description: "Thông tin" },
  tertiary: { label: "Tertiary", description: "Bổ sung / Thử nghiệm" },
};

export const COMPONENTS = [
  {
    id: "accordion",
    category: "Bố cục & Cấu trúc",
    label: "Accordion",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
  },
  {
    id: "alert",
    category: "Phản hồi & Lớp phủ",
    label: "Alert",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "confirm",
    category: "Phản hồi & Lớp phủ",
    label: "Confirm",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "aspect-ratio",
    category: "Bố cục & Cấu trúc",
    label: "Aspect Ratio",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "avatar",
    category: "Hiển thị Dữ liệu",
    label: "Avatar",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "badge",
    category: "Hiển thị Dữ liệu",
    label: "Badge",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "breadcrumb",
    category: "Điều hướng",
    label: "Breadcrumb",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
  },
  {
    id: "button",
    category: "Biểu mẫu & Đầu vào",
    label: "Button",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "calendar",
    category: "Biểu mẫu & Đầu vào",
    label: "Calendar",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "card",
    category: "Bố cục & Cấu trúc",
    label: "Card",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "carousel",
    category: "Bố cục & Cấu trúc",
    label: "Carousel",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
  },
  {
    id: "chart",
    category: "Hiển thị Dữ liệu",
    label: "Chart",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "checkbox",
    category: "Biểu mẫu & Đầu vào",
    label: "Checkbox",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "collapsible",
    category: "Bố cục & Cấu trúc",
    label: "Collapsible",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "combobox",
    category: "Biểu mẫu & Đầu vào",
    label: "Combobox",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "command",
    category: "Điều hướng",
    label: "Command",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "context-menu",
    category: "Điều hướng",
    label: "Context Menu",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "dialog",
    category: "Phản hồi & Lớp phủ",
    label: "Dialog",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "drawer",
    category: "Phản hồi & Lớp phủ",
    label: "Drawer",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "dropdown-menu",
    category: "Điều hướng",
    label: "Dropdown Menu",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "empty",
    category: "Hiển thị Dữ liệu",
    label: "Empty",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
  },

  {
    id: "hover-card",
    category: "Phản hồi & Lớp phủ",
    label: "Hover Card",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "input",
    category: "Biểu mẫu & Đầu vào",
    label: "Input",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "input-group",
    category: "Biểu mẫu & Đầu vào",
    label: "Input Group",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "input-otp",
    category: "Biểu mẫu & Đầu vào",
    label: "Input Otp",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "item",
    category: "Hiển thị Dữ liệu",
    label: "Item",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "kbd",
    category: "Hiển thị Dữ liệu",
    label: "Kbd",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "label",
    category: "Biểu mẫu & Đầu vào",
    label: "Label",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "menubar",
    category: "Điều hướng",
    label: "Menubar",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "navigation-menu",
    category: "Điều hướng",
    label: "Navigation Menu",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "pagination",
    category: "Điều hướng",
    label: "Pagination",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "popover",
    category: "Phản hồi & Lớp phủ",
    label: "Popover",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "progress",
    category: "Phản hồi & Lớp phủ",
    label: "Progress",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "radio-group",
    category: "Biểu mẫu & Đầu vào",
    label: "Radio Group",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "resizable",
    category: "Bố cục & Cấu trúc",
    label: "Resizable",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "scroll-area",
    category: "Bố cục & Cấu trúc",
    label: "Scroll Area",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "select",
    category: "Biểu mẫu & Đầu vào",
    label: "Select",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "separator",
    category: "Bố cục & Cấu trúc",
    label: "Separator",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "sheet",
    category: "Phản hồi & Lớp phủ",
    label: "Sheet",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "sidebar",
    category: "Bố cục & Cấu trúc",
    label: "Sidebar",
    hasMicro: true,
    hasMacro: false,
  },
  {
    id: "skeleton",
    category: "Phản hồi & Lớp phủ",
    label: "Skeleton",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "slider",
    category: "Biểu mẫu & Đầu vào",
    label: "Slider",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "sonner",
    category: "Phản hồi & Lớp phủ",
    label: "Sonner",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "spinner",
    category: "Phản hồi & Lớp phủ",
    label: "Spinner",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "switch",
    category: "Biểu mẫu & Đầu vào",
    label: "Switch",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "table",
    category: "Bố cục & Cấu trúc",
    label: "Table",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
  },
  {
    id: "tabs",
    category: "Điều hướng",
    label: "Tabs",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
  },
  {
    id: "textarea",
    category: "Biểu mẫu & Đầu vào",
    label: "Textarea",
    hasMicro: true,
    hasMacro: true,
    status: "stable",
    hasSize: true,
  },
  {
    id: "toggle",
    category: "Biểu mẫu & Đầu vào",
    label: "Toggle",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "toggle-group",
    category: "Biểu mẫu & Đầu vào",
    label: "Toggle Group",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "tooltip",
    category: "Phản hồi & Lớp phủ",
    label: "Tooltip",
    hasMicro: true,
    hasMacro: false,
    status: "stable",
    hasSize: true,
  },
  {
    id: "dashboard-block",
    category: "Dashboard",
    label: "Dashboard",
    hasMicro: false,
    hasMacro: false,
    status: "new",
  },
  {
    id: "settings-block",
    category: "Cài đặt",
    label: "Giao diện Cài đặt",
    hasMicro: false,
    hasMacro: false,
    status: "new",
  },
  {
    id: "auth-form-block",
    category: "Xác thực",
    label: "Form Đăng nhập",
    hasMicro: false,
    hasMacro: false,
    status: "new",
  },
  {
    id: "auth-recovery-block",
    category: "Xác thực",
    label: "Khôi phục Mật khẩu",
    hasMicro: false,
    hasMacro: false,
    status: "new",
  },
  {
    id: "auth-split-block",
    category: "Xác thực",
    label: "Đăng nhập (Chia màn hình)",
    hasMicro: false,
    hasMacro: false,
    status: "new",
  },
];
